//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>About Page</summary>
	[PublishedModel("aboutPage")]
	public partial class AboutPage : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "aboutPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<AboutPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public AboutPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// About - Contact Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutContactEmail")]
		public virtual string AboutContactEmail => this.Value<string>(_publishedValueFallback, "aboutContactEmail");

		///<summary>
		/// About - Contact Email Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutContactEmailText")]
		public virtual string AboutContactEmailText => this.Value<string>(_publishedValueFallback, "aboutContactEmailText");

		///<summary>
		/// About - Contact Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutContactHeadline")]
		public virtual string AboutContactHeadline => this.Value<string>(_publishedValueFallback, "aboutContactHeadline");

		///<summary>
		/// About - Contact Headline Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutContactHeadlineTwo")]
		public virtual string AboutContactHeadlineTwo => this.Value<string>(_publishedValueFallback, "aboutContactHeadlineTwo");

		///<summary>
		/// About - Contact Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutContactImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutContactImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutContactImage");

		///<summary>
		/// About - Contact Loc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutContactLoc")]
		public virtual string AboutContactLoc => this.Value<string>(_publishedValueFallback, "aboutContactLoc");

		///<summary>
		/// About - Contact Loc Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutContactLocText")]
		public virtual string AboutContactLocText => this.Value<string>(_publishedValueFallback, "aboutContactLocText");

		///<summary>
		/// About - Contact Phone
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutContactPhone")]
		public virtual string AboutContactPhone => this.Value<string>(_publishedValueFallback, "aboutContactPhone");

		///<summary>
		/// About - Contact Phone Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutContactPhoneText")]
		public virtual string AboutContactPhoneText => this.Value<string>(_publishedValueFallback, "aboutContactPhoneText");

		///<summary>
		/// About - Fourth Card One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthCardOne")]
		public virtual string AboutFourthCardOne => this.Value<string>(_publishedValueFallback, "aboutFourthCardOne");

		///<summary>
		/// About - Fourth Card Text One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthCardTextOne")]
		public virtual string AboutFourthCardTextOne => this.Value<string>(_publishedValueFallback, "aboutFourthCardTextOne");

		///<summary>
		/// About - Fourth Card Text Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthCardTextThree")]
		public virtual string AboutFourthCardTextThree => this.Value<string>(_publishedValueFallback, "aboutFourthCardTextThree");

		///<summary>
		/// About - Fourth Card Text Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthCardTextTwo")]
		public virtual string AboutFourthCardTextTwo => this.Value<string>(_publishedValueFallback, "aboutFourthCardTextTwo");

		///<summary>
		/// About - Fourth Card Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthCardThree")]
		public virtual string AboutFourthCardThree => this.Value<string>(_publishedValueFallback, "aboutFourthCardThree");

		///<summary>
		/// About - Fourth Card Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthCardTwo")]
		public virtual string AboutFourthCardTwo => this.Value<string>(_publishedValueFallback, "aboutFourthCardTwo");

		///<summary>
		/// About - Fourth Expert Head Four
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthExpertHeadFour")]
		public virtual string AboutFourthExpertHeadFour => this.Value<string>(_publishedValueFallback, "aboutFourthExpertHeadFour");

		///<summary>
		/// About - Fourth Expert Head One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthExpertHeadOne")]
		public virtual string AboutFourthExpertHeadOne => this.Value<string>(_publishedValueFallback, "aboutFourthExpertHeadOne");

		///<summary>
		/// About - Fourth Expert Head Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthExpertHeadThree")]
		public virtual string AboutFourthExpertHeadThree => this.Value<string>(_publishedValueFallback, "aboutFourthExpertHeadThree");

		///<summary>
		/// About - Fourth Expert Head Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthExpertHeadTwo")]
		public virtual string AboutFourthExpertHeadTwo => this.Value<string>(_publishedValueFallback, "aboutFourthExpertHeadTwo");

		///<summary>
		/// About - Fourth Expert Image Four
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthExpertImageFour")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutFourthExpertImageFour => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutFourthExpertImageFour");

		///<summary>
		/// About - Fourth Expert Image One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthExpertImageOne")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutFourthExpertImageOne => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutFourthExpertImageOne");

		///<summary>
		/// About - Fourth Expert Image Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthExpertImageThree")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutFourthExpertImageThree => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutFourthExpertImageThree");

		///<summary>
		/// About - Fourth Expert Image Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthExpertImageTwo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutFourthExpertImageTwo => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutFourthExpertImageTwo");

		///<summary>
		/// About - Fourth Expert Text Four
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthExpertTextFour")]
		public virtual string AboutFourthExpertTextFour => this.Value<string>(_publishedValueFallback, "aboutFourthExpertTextFour");

		///<summary>
		/// About - Fourth Expert Text One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthExpertTextOne")]
		public virtual string AboutFourthExpertTextOne => this.Value<string>(_publishedValueFallback, "aboutFourthExpertTextOne");

		///<summary>
		/// About - Fourth Expert Text Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthExpertTextThree")]
		public virtual string AboutFourthExpertTextThree => this.Value<string>(_publishedValueFallback, "aboutFourthExpertTextThree");

		///<summary>
		/// About - Fourth Expert Text Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthExpertTextTwo")]
		public virtual string AboutFourthExpertTextTwo => this.Value<string>(_publishedValueFallback, "aboutFourthExpertTextTwo");

		///<summary>
		/// About - Fourth Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthHeadline")]
		public virtual string AboutFourthHeadline => this.Value<string>(_publishedValueFallback, "aboutFourthHeadline");

		///<summary>
		/// About - Fourth Headline Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthHeadlineTwo")]
		public virtual string AboutFourthHeadlineTwo => this.Value<string>(_publishedValueFallback, "aboutFourthHeadlineTwo");

		///<summary>
		/// About - Fourth Image One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthImageOne")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutFourthImageOne => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutFourthImageOne");

		///<summary>
		/// About - Fourth Image Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthImageThree")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutFourthImageThree => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutFourthImageThree");

		///<summary>
		/// About - Fourth Image Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthImageTwo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutFourthImageTwo => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutFourthImageTwo");

		///<summary>
		/// About - Fourth Section Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutFourthSectionTitle")]
		public virtual string AboutFourthSectionTitle => this.Value<string>(_publishedValueFallback, "aboutFourthSectionTitle");

		///<summary>
		/// About - Second Headline Quote
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSecondHeadlineQuote")]
		public virtual string AboutSecondHeadlineQuote => this.Value<string>(_publishedValueFallback, "aboutSecondHeadlineQuote");

		///<summary>
		/// About - Second Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSecondImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutSecondImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutSecondImage");

		///<summary>
		/// About - Second Image Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSecondImageText")]
		public virtual string AboutSecondImageText => this.Value<string>(_publishedValueFallback, "aboutSecondImageText");

		///<summary>
		/// About - Second Text Five
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSecondTextFive")]
		public virtual string AboutSecondTextFive => this.Value<string>(_publishedValueFallback, "aboutSecondTextFive");

		///<summary>
		/// About - Second Text Four
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSecondTextFour")]
		public virtual string AboutSecondTextFour => this.Value<string>(_publishedValueFallback, "aboutSecondTextFour");

		///<summary>
		/// About - Second Text One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSecondTextOne")]
		public virtual string AboutSecondTextOne => this.Value<string>(_publishedValueFallback, "aboutSecondTextOne");

		///<summary>
		/// About - Second Text Seven
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSecondTextSeven")]
		public virtual string AboutSecondTextSeven => this.Value<string>(_publishedValueFallback, "aboutSecondTextSeven");

		///<summary>
		/// About - Second Text Six
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSecondTextSix")]
		public virtual string AboutSecondTextSix => this.Value<string>(_publishedValueFallback, "aboutSecondTextSix");

		///<summary>
		/// About - Second Text Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSecondTextThree")]
		public virtual string AboutSecondTextThree => this.Value<string>(_publishedValueFallback, "aboutSecondTextThree");

		///<summary>
		/// About - Second Text Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSecondTextTwo")]
		public virtual string AboutSecondTextTwo => this.Value<string>(_publishedValueFallback, "aboutSecondTextTwo");

		///<summary>
		/// About - Third Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutThirdHeadline")]
		public virtual string AboutThirdHeadline => this.Value<string>(_publishedValueFallback, "aboutThirdHeadline");

		///<summary>
		/// About - Third Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutThirdImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutThirdImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutThirdImage");

		///<summary>
		/// About - Third Kevin
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutThirdKevin")]
		public virtual string AboutThirdKevin => this.Value<string>(_publishedValueFallback, "aboutThirdKevin");

		///<summary>
		/// About - Third Section Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutThirdSectionTitle")]
		public virtual string AboutThirdSectionTitle => this.Value<string>(_publishedValueFallback, "aboutThirdSectionTitle");

		///<summary>
		/// About - Third Swebank
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutThirdSwebank")]
		public virtual string AboutThirdSwebank => this.Value<string>(_publishedValueFallback, "aboutThirdSwebank");

		///<summary>
		/// About - Third Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutThirdText")]
		public virtual string AboutThirdText => this.Value<string>(_publishedValueFallback, "aboutThirdText");

		///<summary>
		/// About - Top About Nav Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTopAboutNavText")]
		public virtual string AboutTopAboutNavText => this.Value<string>(_publishedValueFallback, "aboutTopAboutNavText");

		///<summary>
		/// About - Top Head Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTopHeadImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutTopHeadImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutTopHeadImage");

		///<summary>
		/// About - Top Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTopHeadline")]
		public virtual string AboutTopHeadline => this.Value<string>(_publishedValueFallback, "aboutTopHeadline");

		///<summary>
		/// About - Top Home Nav Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTopHomeNavText")]
		public virtual string AboutTopHomeNavText => this.Value<string>(_publishedValueFallback, "aboutTopHomeNavText");

		///<summary>
		/// About - Top Home Nav Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTopHomeNavUrl")]
		public virtual string AboutTopHomeNavUrl => this.Value<string>(_publishedValueFallback, "aboutTopHomeNavUrl");

		///<summary>
		/// Footer Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerText")]
		public virtual string FooterText => this.Value<string>(_publishedValueFallback, "footerText");

		///<summary>
		/// Footer Text Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerTextTwo")]
		public virtual string FooterTextTwo => this.Value<string>(_publishedValueFallback, "footerTextTwo");

		///<summary>
		/// Header - About Nav Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerAboutNavText")]
		public virtual string HeaderAboutNavText => this.Value<string>(_publishedValueFallback, "headerAboutNavText");

		///<summary>
		/// Header - About Nav Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerAboutNavUrl")]
		public virtual string HeaderAboutNavUrl => this.Value<string>(_publishedValueFallback, "headerAboutNavUrl");

		///<summary>
		/// Header - Address Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerAddressText")]
		public virtual string HeaderAddressText => this.Value<string>(_publishedValueFallback, "headerAddressText");

		///<summary>
		/// Header - Contact Nav Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerContactNavUrl")]
		public virtual string HeaderContactNavUrl => this.Value<string>(_publishedValueFallback, "headerContactNavUrl");

		///<summary>
		/// Header - Contacts Nav Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerContactsNavText")]
		public virtual string HeaderContactsNavText => this.Value<string>(_publishedValueFallback, "headerContactsNavText");

		///<summary>
		/// Header - Home Nav Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerHomeNavUrl")]
		public virtual string HeaderHomeNavUrl => this.Value<string>(_publishedValueFallback, "headerHomeNavUrl");

		///<summary>
		/// Header - Projects Nav Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerProjectsNavText")]
		public virtual string HeaderProjectsNavText => this.Value<string>(_publishedValueFallback, "headerProjectsNavText");

		///<summary>
		/// Header - Projects Nav Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerProjectsNavUrl")]
		public virtual string HeaderProjectsNavUrl => this.Value<string>(_publishedValueFallback, "headerProjectsNavUrl");

		///<summary>
		/// Header - Service Nav Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerServiceNavText")]
		public virtual string HeaderServiceNavText => this.Value<string>(_publishedValueFallback, "headerServiceNavText");

		///<summary>
		/// Header - Services Nav Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerServicesNavUrl")]
		public virtual string HeaderServicesNavUrl => this.Value<string>(_publishedValueFallback, "headerServicesNavUrl");

		///<summary>
		/// Onatrix Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("onatrixImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OnatrixImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "onatrixImage");

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => this.Value<string>(_publishedValueFallback, "pageTitle");
	}
}
