//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Projects Page</summary>
	[PublishedModel("projectsPage")]
	public partial class ProjectsPage : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "projectsPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<ProjectsPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ProjectsPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Footer Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerText")]
		public virtual string FooterText => this.Value<string>(_publishedValueFallback, "footerText");

		///<summary>
		/// Footer Text Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerTextTwo")]
		public virtual string FooterTextTwo => this.Value<string>(_publishedValueFallback, "footerTextTwo");

		///<summary>
		/// Header - About Nav Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerAboutNavText")]
		public virtual string HeaderAboutNavText => this.Value<string>(_publishedValueFallback, "headerAboutNavText");

		///<summary>
		/// Header - About Nav Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerAboutNavUrl")]
		public virtual string HeaderAboutNavUrl => this.Value<string>(_publishedValueFallback, "headerAboutNavUrl");

		///<summary>
		/// Header - Contact Nav Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerContactNavText")]
		public virtual string HeaderContactNavText => this.Value<string>(_publishedValueFallback, "headerContactNavText");

		///<summary>
		/// Header - Contact Nav Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerContactNavUrl")]
		public virtual string HeaderContactNavUrl => this.Value<string>(_publishedValueFallback, "headerContactNavUrl");

		///<summary>
		/// Header - Home Nav Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerHomeNavUrl")]
		public virtual string HeaderHomeNavUrl => this.Value<string>(_publishedValueFallback, "headerHomeNavUrl");

		///<summary>
		/// Header - Projects Nav Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerProjectsNavText")]
		public virtual string HeaderProjectsNavText => this.Value<string>(_publishedValueFallback, "headerProjectsNavText");

		///<summary>
		/// Header - Projects Nav Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerProjectsNavUrl")]
		public virtual string HeaderProjectsNavUrl => this.Value<string>(_publishedValueFallback, "headerProjectsNavUrl");

		///<summary>
		/// Header - Services Nav Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerServicesNavText")]
		public virtual string HeaderServicesNavText => this.Value<string>(_publishedValueFallback, "headerServicesNavText");

		///<summary>
		/// Header - Services Nav Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerServicesNavUrl")]
		public virtual string HeaderServicesNavUrl => this.Value<string>(_publishedValueFallback, "headerServicesNavUrl");

		///<summary>
		/// Header - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerText")]
		public virtual string HeaderText => this.Value<string>(_publishedValueFallback, "headerText");

		///<summary>
		/// Onatrix Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("onatrixImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OnatrixImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "onatrixImage");

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => this.Value<string>(_publishedValueFallback, "pageTitle");

		///<summary>
		/// Project Card - Date Four
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCardDateFour")]
		public virtual string ProjectCardDateFour => this.Value<string>(_publishedValueFallback, "projectCardDateFour");

		///<summary>
		/// Project Card - Date One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCardDateOne")]
		public virtual string ProjectCardDateOne => this.Value<string>(_publishedValueFallback, "projectCardDateOne");

		///<summary>
		/// Project Card - Date Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCardDateThree")]
		public virtual string ProjectCardDateThree => this.Value<string>(_publishedValueFallback, "projectCardDateThree");

		///<summary>
		/// Project Card - Date Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCardDateTwo")]
		public virtual string ProjectCardDateTwo => this.Value<string>(_publishedValueFallback, "projectCardDateTwo");

		///<summary>
		/// Project Card - Headline Four
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCardHeadlineFour")]
		public virtual string ProjectCardHeadlineFour => this.Value<string>(_publishedValueFallback, "projectCardHeadlineFour");

		///<summary>
		/// Project Card - Headline One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCardHeadlineOne")]
		public virtual string ProjectCardHeadlineOne => this.Value<string>(_publishedValueFallback, "projectCardHeadlineOne");

		///<summary>
		/// Project Card - Headline Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCardHeadlineThree")]
		public virtual string ProjectCardHeadlineThree => this.Value<string>(_publishedValueFallback, "projectCardHeadlineThree");

		///<summary>
		/// Project Card - Headline Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCardHeadlineTwo")]
		public virtual string ProjectCardHeadlineTwo => this.Value<string>(_publishedValueFallback, "projectCardHeadlineTwo");

		///<summary>
		/// Project Card - Image Four
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCardImageFour")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectCardImageFour => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectCardImageFour");

		///<summary>
		/// Project Card - Image One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCardImageOne")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectCardImageOne => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectCardImageOne");

		///<summary>
		/// Project Card - Image Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCardImageThree")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectCardImageThree => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectCardImageThree");

		///<summary>
		/// Project Card - Image Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCardImageTwo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectCardImageTwo => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectCardImageTwo");

		///<summary>
		/// Project Card - Read More One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCardReadMoreOne")]
		public virtual string ProjectCardReadMoreOne => this.Value<string>(_publishedValueFallback, "projectCardReadMoreOne");

		///<summary>
		/// Project Card - Text One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectCardTextOne")]
		public virtual string ProjectCardTextOne => this.Value<string>(_publishedValueFallback, "projectCardTextOne");

		///<summary>
		/// Project Contact - Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactEmail")]
		public virtual string ProjectContactEmail => this.Value<string>(_publishedValueFallback, "projectContactEmail");

		///<summary>
		/// Project Contact - Email Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactEmailText")]
		public virtual string ProjectContactEmailText => this.Value<string>(_publishedValueFallback, "projectContactEmailText");

		///<summary>
		/// Project Contact - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactHeadline")]
		public virtual string ProjectContactHeadline => this.Value<string>(_publishedValueFallback, "projectContactHeadline");

		///<summary>
		/// Project Contact - Headline Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactHeadlineTwo")]
		public virtual string ProjectContactHeadlineTwo => this.Value<string>(_publishedValueFallback, "projectContactHeadlineTwo");

		///<summary>
		/// Project Contact - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectContactImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectContactImage");

		///<summary>
		/// Project Contact - Loc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactLoc")]
		public virtual string ProjectContactLoc => this.Value<string>(_publishedValueFallback, "projectContactLoc");

		///<summary>
		/// Project Contact - Loc Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactLocText")]
		public virtual string ProjectContactLocText => this.Value<string>(_publishedValueFallback, "projectContactLocText");

		///<summary>
		/// Project Contact - Phone
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactPhone")]
		public virtual string ProjectContactPhone => this.Value<string>(_publishedValueFallback, "projectContactPhone");

		///<summary>
		/// Project Contact - Phone Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactPhoneText")]
		public virtual string ProjectContactPhoneText => this.Value<string>(_publishedValueFallback, "projectContactPhoneText");

		///<summary>
		/// Project Online - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectOnlineHeadline")]
		public virtual string ProjectOnlineHeadline => this.Value<string>(_publishedValueFallback, "projectOnlineHeadline");

		///<summary>
		/// Project Online - Input
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectOnlineInput")]
		public virtual string ProjectOnlineInput => this.Value<string>(_publishedValueFallback, "projectOnlineInput");

		///<summary>
		/// Project Online - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectOnlineText")]
		public virtual string ProjectOnlineText => this.Value<string>(_publishedValueFallback, "projectOnlineText");

		///<summary>
		/// Project Page - Next
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectPageNext")]
		public virtual string ProjectPageNext => this.Value<string>(_publishedValueFallback, "projectPageNext");

		///<summary>
		/// Project Page - One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectPageOne")]
		public virtual string ProjectPageOne => this.Value<string>(_publishedValueFallback, "projectPageOne");

		///<summary>
		/// Project Page - Prev
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectPagePrev")]
		public virtual string ProjectPagePrev => this.Value<string>(_publishedValueFallback, "projectPagePrev");

		///<summary>
		/// Project Page - Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectPageTwo")]
		public virtual string ProjectPageTwo => this.Value<string>(_publishedValueFallback, "projectPageTwo");

		///<summary>
		/// Project Tags - App
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsApp")]
		public virtual string ProjectTagsApp => this.Value<string>(_publishedValueFallback, "projectTagsApp");

		///<summary>
		/// Project Tags - Business
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsBusiness")]
		public virtual string ProjectTagsBusiness => this.Value<string>(_publishedValueFallback, "projectTagsBusiness");

		///<summary>
		/// Project Tags - Business Plans
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsBusinessPlans")]
		public virtual string ProjectTagsBusinessPlans => this.Value<string>(_publishedValueFallback, "projectTagsBusinessPlans");

		///<summary>
		/// Project Tags - Finance
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsFinance")]
		public virtual string ProjectTagsFinance => this.Value<string>(_publishedValueFallback, "projectTagsFinance");

		///<summary>
		/// Project Tags - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsHeadline")]
		public virtual string ProjectTagsHeadline => this.Value<string>(_publishedValueFallback, "projectTagsHeadline");

		///<summary>
		/// Project Tags - Insights
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsInsights")]
		public virtual string ProjectTagsInsights => this.Value<string>(_publishedValueFallback, "projectTagsInsights");

		///<summary>
		/// Project Tags - Pricing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsPricing")]
		public virtual string ProjectTagsPricing => this.Value<string>(_publishedValueFallback, "projectTagsPricing");

		///<summary>
		/// Project Tags - Project
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsProject")]
		public virtual string ProjectTagsProject => this.Value<string>(_publishedValueFallback, "projectTagsProject");

		///<summary>
		/// Project Tags - Report
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTagsReport")]
		public virtual string ProjectTagsReport => this.Value<string>(_publishedValueFallback, "projectTagsReport");

		///<summary>
		/// Project Top - Head Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTopHeadImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectTopHeadImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectTopHeadImage");

		///<summary>
		/// Project Top - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTopHeadline")]
		public virtual string ProjectTopHeadline => this.Value<string>(_publishedValueFallback, "projectTopHeadline");

		///<summary>
		/// Project Top - Home Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTopHomeText")]
		public virtual string ProjectTopHomeText => this.Value<string>(_publishedValueFallback, "projectTopHomeText");

		///<summary>
		/// Project Top - Home Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTopHomeUrl")]
		public virtual string ProjectTopHomeUrl => this.Value<string>(_publishedValueFallback, "projectTopHomeUrl");

		///<summary>
		/// Project Top - Project Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTopProjectText")]
		public virtual string ProjectTopProjectText => this.Value<string>(_publishedValueFallback, "projectTopProjectText");
	}
}
