//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Services Page</summary>
	[PublishedModel("servicesPage")]
	public partial class ServicesPage : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "servicesPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<ServicesPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ServicesPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Footer Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerText")]
		public virtual string FooterText => this.Value<string>(_publishedValueFallback, "footerText");

		///<summary>
		/// Footer Text Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerTextTwo")]
		public virtual string FooterTextTwo => this.Value<string>(_publishedValueFallback, "footerTextTwo");

		///<summary>
		/// Onatrix Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("onatrixImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OnatrixImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "onatrixImage");

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => this.Value<string>(_publishedValueFallback, "pageTitle");

		///<summary>
		/// Service Cards - Headline Five
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsHeadlineFive")]
		public virtual string ServiceCardsHeadlineFive => this.Value<string>(_publishedValueFallback, "serviceCardsHeadlineFive");

		///<summary>
		/// Service Cards - Headline Four
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsHeadlineFour")]
		public virtual string ServiceCardsHeadlineFour => this.Value<string>(_publishedValueFallback, "serviceCardsHeadlineFour");

		///<summary>
		/// Service Cards - Headline One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsHeadlineOne")]
		public virtual string ServiceCardsHeadlineOne => this.Value<string>(_publishedValueFallback, "serviceCardsHeadlineOne");

		///<summary>
		/// Service Cards - Headline Six
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsHeadlineSix")]
		public virtual string ServiceCardsHeadlineSix => this.Value<string>(_publishedValueFallback, "serviceCardsHeadlineSix");

		///<summary>
		/// Service Cards - Headline Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsHeadlineThree")]
		public virtual string ServiceCardsHeadlineThree => this.Value<string>(_publishedValueFallback, "serviceCardsHeadlineThree");

		///<summary>
		/// Service Cards - Headline Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsHeadlineTwo")]
		public virtual string ServiceCardsHeadlineTwo => this.Value<string>(_publishedValueFallback, "serviceCardsHeadlineTwo");

		///<summary>
		/// Service Cards - Image Five
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsImageFive")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceCardsImageFive => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceCardsImageFive");

		///<summary>
		/// Service Cards - Image Four
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsImageFour")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceCardsImageFour => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceCardsImageFour");

		///<summary>
		/// Service Cards - Image One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsImageOne")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceCardsImageOne => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceCardsImageOne");

		///<summary>
		/// Service Cards - Image Six
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsImageSix")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceCardsImageSix => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceCardsImageSix");

		///<summary>
		/// Service Cards - Image Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsImageThree")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceCardsImageThree => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceCardsImageThree");

		///<summary>
		/// Service Cards - Image Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsImageTwo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceCardsImageTwo => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceCardsImageTwo");

		///<summary>
		/// Service Cards - Text Five
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsTextFive")]
		public virtual string ServiceCardsTextFive => this.Value<string>(_publishedValueFallback, "serviceCardsTextFive");

		///<summary>
		/// Service Cards - Text Four
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsTextFour")]
		public virtual string ServiceCardsTextFour => this.Value<string>(_publishedValueFallback, "serviceCardsTextFour");

		///<summary>
		/// Service Cards - Text One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsTextOne")]
		public virtual string ServiceCardsTextOne => this.Value<string>(_publishedValueFallback, "serviceCardsTextOne");

		///<summary>
		/// Service Cards - Text Six
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsTextSix")]
		public virtual string ServiceCardsTextSix => this.Value<string>(_publishedValueFallback, "serviceCardsTextSix");

		///<summary>
		/// Service Cards - Text Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsTextThree")]
		public virtual string ServiceCardsTextThree => this.Value<string>(_publishedValueFallback, "serviceCardsTextThree");

		///<summary>
		/// Service Cards - Text Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceCardsTextTwo")]
		public virtual string ServiceCardsTextTwo => this.Value<string>(_publishedValueFallback, "serviceCardsTextTwo");

		///<summary>
		/// Service Contact - Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceContactEmail")]
		public virtual string ServiceContactEmail => this.Value<string>(_publishedValueFallback, "serviceContactEmail");

		///<summary>
		/// Service Contact - Email Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceContactEmailText")]
		public virtual string ServiceContactEmailText => this.Value<string>(_publishedValueFallback, "serviceContactEmailText");

		///<summary>
		/// Service Contact - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceContactHeadline")]
		public virtual string ServiceContactHeadline => this.Value<string>(_publishedValueFallback, "serviceContactHeadline");

		///<summary>
		/// Service Contact - Headline Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceContactHeadlineTwo")]
		public virtual string ServiceContactHeadlineTwo => this.Value<string>(_publishedValueFallback, "serviceContactHeadlineTwo");

		///<summary>
		/// Service Contact - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceContactImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceContactImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceContactImage");

		///<summary>
		/// Service Contact - Loc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceContactLoc")]
		public virtual string ServiceContactLoc => this.Value<string>(_publishedValueFallback, "serviceContactLoc");

		///<summary>
		/// Service Contact - Loc Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceContactLocText")]
		public virtual string ServiceContactLocText => this.Value<string>(_publishedValueFallback, "serviceContactLocText");

		///<summary>
		/// Service Contact - Phone
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceContactPhone")]
		public virtual string ServiceContactPhone => this.Value<string>(_publishedValueFallback, "serviceContactPhone");

		///<summary>
		/// Service Contact - Phone Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceContactPhoneText")]
		public virtual string ServiceContactPhoneText => this.Value<string>(_publishedValueFallback, "serviceContactPhoneText");

		///<summary>
		/// Service Middle - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceMiddleHeadline")]
		public virtual string ServiceMiddleHeadline => this.Value<string>(_publishedValueFallback, "serviceMiddleHeadline");

		///<summary>
		/// Service Middle - Headline Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceMiddleHeadlineTwo")]
		public virtual string ServiceMiddleHeadlineTwo => this.Value<string>(_publishedValueFallback, "serviceMiddleHeadlineTwo");

		///<summary>
		/// Service Middle - Page Next
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceMiddlePageNext")]
		public virtual string ServiceMiddlePageNext => this.Value<string>(_publishedValueFallback, "serviceMiddlePageNext");

		///<summary>
		/// Service Middle - Page One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceMiddlePageOne")]
		public virtual string ServiceMiddlePageOne => this.Value<string>(_publishedValueFallback, "serviceMiddlePageOne");

		///<summary>
		/// Service Middle - Page Prev
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceMiddlePagePrev")]
		public virtual string ServiceMiddlePagePrev => this.Value<string>(_publishedValueFallback, "serviceMiddlePagePrev");

		///<summary>
		/// Service Middle - Page Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceMiddlePageTwo")]
		public virtual string ServiceMiddlePageTwo => this.Value<string>(_publishedValueFallback, "serviceMiddlePageTwo");

		///<summary>
		/// Services - About Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servicesAboutUrl")]
		public virtual string ServicesAboutUrl => this.Value<string>(_publishedValueFallback, "servicesAboutUrl");

		///<summary>
		/// Services - About Url Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servicesAboutUrlText")]
		public virtual string ServicesAboutUrlText => this.Value<string>(_publishedValueFallback, "servicesAboutUrlText");

		///<summary>
		/// Services - Contact Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servicesContactUrl")]
		public virtual string ServicesContactUrl => this.Value<string>(_publishedValueFallback, "servicesContactUrl");

		///<summary>
		/// Services - Contact Url Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servicesContactUrlText")]
		public virtual string ServicesContactUrlText => this.Value<string>(_publishedValueFallback, "servicesContactUrlText");

		///<summary>
		/// Services - Header text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servicesHeaderText")]
		public virtual string ServicesHeaderText => this.Value<string>(_publishedValueFallback, "servicesHeaderText");

		///<summary>
		/// Services - Home Nav Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servicesHomeNavUrl")]
		public virtual string ServicesHomeNavUrl => this.Value<string>(_publishedValueFallback, "servicesHomeNavUrl");

		///<summary>
		/// Services - Projects Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servicesProjectsUrl")]
		public virtual string ServicesProjectsUrl => this.Value<string>(_publishedValueFallback, "servicesProjectsUrl");

		///<summary>
		/// Services - Projects Url Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servicesProjectsUrlText")]
		public virtual string ServicesProjectsUrlText => this.Value<string>(_publishedValueFallback, "servicesProjectsUrlText");

		///<summary>
		/// Services - Services Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servicesServicesUrl")]
		public virtual string ServicesServicesUrl => this.Value<string>(_publishedValueFallback, "servicesServicesUrl");

		///<summary>
		/// Services - Services Url Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servicesServicesUrlText")]
		public virtual string ServicesServicesUrlText => this.Value<string>(_publishedValueFallback, "servicesServicesUrlText");

		///<summary>
		/// Service Top - Head Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceTopHeadImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceTopHeadImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceTopHeadImage");

		///<summary>
		/// Service Top - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceTopHeadline")]
		public virtual string ServiceTopHeadline => this.Value<string>(_publishedValueFallback, "serviceTopHeadline");

		///<summary>
		/// Service Top - Home Nav Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceTopHomeNavText")]
		public virtual string ServiceTopHomeNavText => this.Value<string>(_publishedValueFallback, "serviceTopHomeNavText");

		///<summary>
		/// Service Top - Home Nav Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceTopHomeNavUrl")]
		public virtual string ServiceTopHomeNavUrl => this.Value<string>(_publishedValueFallback, "serviceTopHomeNavUrl");

		///<summary>
		/// Service Top - ServiceText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceTopServiceText")]
		public virtual string ServiceTopServiceText => this.Value<string>(_publishedValueFallback, "serviceTopServiceText");
	}
}
